const math = @import("math.zig");

const Vec2i = math.Vec2i;

pub const InputKey = enum(c_uint) {
    invalid,
    // Gamepad
    gamepad_dpad_down,
    gamepad_dpad_up,
    gamepad_dpad_left,
    gamepad_dpad_right,
    gamepad_face_button_north,  // xbox y
    gamepad_face_button_south,  // xbox a
    gamepad_face_button_east,   // xbox b
    gamepad_face_button_west,   // xbox x
    gamepad_start,
    gamepad_back,
    gamepad_left_shoulder,      // ps l1
    gamepad_left_trigger,       // ps l2
    gamepad_left_analog_button, // ps l3
    gamepad_left_analog_2d_axis_x,
    gamepad_left_analog_2d_axis_y,
    gamepad_right_shoulder,      // ps r1
    gamepad_right_trigger,       // ps r2
    gamepad_right_analog_button, // ps r3
    gamepad_right_analog_2d_axis_x,
    gamepad_right_analog_2d_axis_y,
    gamepad_left_analog_left,
    gamepad_left_analog_right,
    gamepad_left_analog_up,
    gamepad_left_analog_down,
    gamepad_right_analog_left,
    gamepad_right_analog_right,
    gamepad_right_analog_up,
    gamepad_right_analog_down,
    // Keyboard
    keyboard_tab,
    keyboard_left,
    keyboard_right,
    keyboard_up,
    keyboard_down,
    keyboard_page_down,
    keyboard_page_up,
    keyboard_home,
    keyboard_end,
    keyboard_insert,
    keyboard_delete,
    keyboard_backspace,
    keyboard_space,
    keyboard_return,
    keyboard_escape,
    keyboard_quote,
    keyboard_comma,
    keyboard_minus,
    keyboard_period,
    keyboard_slash,
    keyboard_semicolon,
    keyboard_equals,
    keyboard_left_bracket,
    keyboard_right_bracket,
    keyboard_backslash,
    keyboard_backquote,
    keyboard_caps_lock,
    keyboard_scroll_lock,
    keyboard_num_lock_clear,
    keyboard_print_screen,
    keyboard_pause,
    keyboard_keypad_0,
    keyboard_keypad_1,
    keyboard_keypad_2,
    keyboard_keypad_3,
    keyboard_keypad_4,
    keyboard_keypad_5,
    keyboard_keypad_6,
    keyboard_keypad_7,
    keyboard_keypad_8,
    keyboard_keypad_9,
    keyboard_keypad_period,
    keyboard_keypad_divide,
    keyboard_keypad_multiply,
    keyboard_keypad_minus,
    keyboard_keypad_plus,
    keyboard_keypad_enter,
    keyboard_keypad_equals,
    keyboard_left_control,
    keyboard_left_shift,
    keyboard_left_alt,
    keyboard_left_gui,
    keyboard_right_control,
    keyboard_right_shift,
    keyboard_right_alt,
    keyboard_right_gui,
    keyboard_application,
    keyboard_num_0,
    keyboard_num_1,
    keyboard_num_2,
    keyboard_num_3,
    keyboard_num_4,
    keyboard_num_5,
    keyboard_num_6,
    keyboard_num_7,
    keyboard_num_8,
    keyboard_num_9,
    keyboard_a,
    keyboard_b,
    keyboard_c,
    keyboard_d,
    keyboard_e,
    keyboard_f,
    keyboard_g,
    keyboard_h,
    keyboard_i,
    keyboard_j,
    keyboard_k,
    keyboard_l,
    keyboard_m,
    keyboard_n,
    keyboard_o,
    keyboard_p,
    keyboard_q,
    keyboard_r,
    keyboard_s,
    keyboard_t,
    keyboard_u,
    keyboard_v,
    keyboard_w,
    keyboard_x,
    keyboard_y,
    keyboard_z,
    keyboard_f1,
    keyboard_f2,
    keyboard_f3,
    keyboard_f4,
    keyboard_f5,
    keyboard_f6,
    keyboard_f7,
    keyboard_f8,
    keyboard_f9,
    keyboard_f10,
    keyboard_f11,
    keyboard_f12,
    keyboard_f13,
    keyboard_f14,
    keyboard_f15,
    keyboard_f16,
    keyboard_f17,
    keyboard_f18,
    keyboard_f19,
    keyboard_f20,
    keyboard_f21,
    keyboard_f22,
    keyboard_f23,
    keyboard_f24,
    keyboard_app_forward,
    keyboard_app_back,
    // mouse
    mouse_button_left,
    mouse_button_right,
    mouse_button_middle,
};


pub fn register_mouse_move_event(new_position: Vec2i) void {
    _ = new_position;
}